javascript:(function(){var openWindow=window.open('');
var url=window.document.URL.toString();
var src=document.documentElement.innerHTML;
var note='book';form=document.createElement('form');
form.setAttribute('method','POST');
form.setAttribute('action','https://www.tubeoffline.com/downloadFrom.php');
form.setAttribute('onsubmit','Submit.disabled = true;return true;');srcPlaceholder=document.createElement('input');
srcPlaceholder.setAttribute('name','src');srcPlaceholder.setAttribute('type','hidden');
srcPlaceholder.setAttribute('value',src);
form.appendChild(srcPlaceholder);urlPlaceholder=document.createElement('input');
urlPlaceholder.setAttribute('name','url');urlPlaceholder.setAttribute('type','hidden');
urlPlaceholder.setAttribute('value',url);form.appendChild(urlPlaceholder);
notePlaceholder=document.createElement('input');notePlaceholder.setAttribute('name','note');
notePlaceholder.setAttribute('type','hidden');
notePlaceholder.setAttribute('value',note);form.appendChild(notePlaceholder);
divPlaceholder=document.createElement('div');
divPlaceholder.setAttribute('name','label');
divPlaceholder.setAttribute('type','div');divPlaceholder.style.textAlign='center';
divPlaceholder.style.fontWeight='bold';
divPlaceholder.style.fontSize='18px';
divPlaceholder.style.fontFamily='arial';
divPlaceholder.innerHTML='<br><br>Click the below button to Continue.<br>If your download does not work, please send feedback so we fix it for you.<br><br>';
form.appendChild(divPlaceholder);btn=document.createElement('input');
btn.setAttribute('name','Submit');btn.setAttribute('type','submit');
btn.setAttribute('value','Go To TubeOffline download page >>');
btn.style.fontSize='24px';
btn.style.fontWeight='bold';btn.style.color='#FA8507';
btn.style.width='600px';
btn.style.height='100px';
btn.style.display='table';
btn.style.margin='0 auto';btn.setAttribute('onclick',"this.value='Converting Video, Please wait...'");
form.appendChild(btn);openWindow.document.body.appendChild(form)})();